### ISSUE TITLE
[SUGESTÃO] Adicionar uma documentação mais detalhada ao seu projeto.

### ISSUE THREAD

**Issue by BrenaPaiva** [mayumicast/Pratic#2]
Por exemplo:
# Nome do Projeto

Descrição concisa do seu projeto.

## Índice

- Funcionalidades
- Demonstração da Aplicação
- Tecnologias Utilizadas
- Como Contribuir
- Licença

## Funcionalidades

- Liste aqui as principais funcionalidades do seu projeto.

## Demonstração da Aplicação 🚨

- Inclua um link ou instruções para acessar a aplicação em funcionamento.

## Tecnologias Utilizadas

- Liste as tecnologias, linguagens e frameworks utilizados no projeto.

## Como Contribuir

- Explique como outros desenvolvedores podem contribuir para o seu projeto.

## Licença

Este projeto está sob a licença XYZ. Veja o arquivo LICENSE para mais detalhes.

**Comment by mayumicast** [comment]
Opa, certo. Irei adicionar, obrigada!!

**Comment by mayumicast** [comment]
THAKS

**Comment by mayumicast** [comment]
> Por exemplo:
> 
> # Nome do Projeto
> Descrição concisa do seu projeto.
> 
> ## Índice
> * Funcionalidades
> * Demonstração da Aplicação
> * Tecnologias Utilizadas
> * Como contribuir
> * Licença
> 
> ## Funcionalidades
> * Liste aqui as principais funcionalidades do seu projeto.
> 
> ## Demonstração da Aplicação 🚨
> * Inclui um link ou instruções para acessar a aplicação em funcionamento.
> 
> ## Tecnologias Utilizadas
> * Listar as tecnologias, linguagens e frameworks utilizados no projeto.
> 
> ## Como contribuir
> * Explique como outros desenvolvedores podem contribuir para o seu projeto.
> 
> ## Licença
> Este projeto está sob licença XYZ. Veja o arquivo LICENSE para mais detalhes.
